### ISSUE TITLE
Failing when update is available for CI integration

### ISSUE THREAD

**Issue by andmos** [seesharper/dotnet-deps#6]
It would be great with some switch/flag that changed the exitcode if an update is available for any package in a `csproj` or `nuspec` file. In that way, a CI build could be set up to run frequently and fail if an update is available that should be looked at.
Something like this should do the trick:
```shell
$ dotnet-deps
We found 7 😢 dependencies. For 🍺, type 'deps --update'
$ echo $?
1
```

That will integrate quite well with any CI tool.

**Comment by seesharper** [comment]
Closing this by #7 for now. Feel free to reopen if the need for a custom exit code should arise 👍
